version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - finservice_network
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: poke-db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - finservice_network
    restart: always

networks:
  finservice_network:
    driver: bridge